/*
 * Generated by gdbus-codegen 2.50.3. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __MY_GEN_H__
#define __MY_GEN_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.gtk.GDBus.Example.ObjectManager.Animal */

#define BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL (bjs_org_gtk_gdbus_example_object_manager_animal_get_type ())
#define BJS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL, BjsOrgGtkGDBusExampleObjectManagerAnimal))
#define BJS_IS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL))
#define BJS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL, BjsOrgGtkGDBusExampleObjectManagerAnimalIface))

struct _BjsOrgGtkGDBusExampleObjectManagerAnimal;
typedef struct _BjsOrgGtkGDBusExampleObjectManagerAnimal BjsOrgGtkGDBusExampleObjectManagerAnimal;
typedef struct _BjsOrgGtkGDBusExampleObjectManagerAnimalIface BjsOrgGtkGDBusExampleObjectManagerAnimalIface;

struct _BjsOrgGtkGDBusExampleObjectManagerAnimalIface
{
  GTypeInterface parent_iface;



  gboolean (*handle_poke) (
    BjsOrgGtkGDBusExampleObjectManagerAnimal *object,
    GDBusMethodInvocation *invocation,
    gboolean arg_make_sad,
    gboolean arg_make_happy);

  const gchar * (*get_mood) (BjsOrgGtkGDBusExampleObjectManagerAnimal *object);

  void (*jumped) (
    BjsOrgGtkGDBusExampleObjectManagerAnimal *object,
    gdouble arg_height);

};

GType bjs_org_gtk_gdbus_example_object_manager_animal_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *bjs_org_gtk_gdbus_example_object_manager_animal_interface_info (void);
guint bjs_org_gtk_gdbus_example_object_manager_animal_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void bjs_org_gtk_gdbus_example_object_manager_animal_complete_poke (
    BjsOrgGtkGDBusExampleObjectManagerAnimal *object,
    GDBusMethodInvocation *invocation);



/* D-Bus signal emissions functions: */
void bjs_org_gtk_gdbus_example_object_manager_animal_emit_jumped (
    BjsOrgGtkGDBusExampleObjectManagerAnimal *object,
    gdouble arg_height);



/* D-Bus method calls: */
void bjs_org_gtk_gdbus_example_object_manager_animal_call_poke (
    BjsOrgGtkGDBusExampleObjectManagerAnimal *proxy,
    gboolean arg_make_sad,
    gboolean arg_make_happy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean bjs_org_gtk_gdbus_example_object_manager_animal_call_poke_finish (
    BjsOrgGtkGDBusExampleObjectManagerAnimal *proxy,
    GAsyncResult *res,
    GError **error);

gboolean bjs_org_gtk_gdbus_example_object_manager_animal_call_poke_sync (
    BjsOrgGtkGDBusExampleObjectManagerAnimal *proxy,
    gboolean arg_make_sad,
    gboolean arg_make_happy,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
const gchar *bjs_org_gtk_gdbus_example_object_manager_animal_get_mood (BjsOrgGtkGDBusExampleObjectManagerAnimal *object);
gchar *bjs_org_gtk_gdbus_example_object_manager_animal_dup_mood (BjsOrgGtkGDBusExampleObjectManagerAnimal *object);
void bjs_org_gtk_gdbus_example_object_manager_animal_set_mood (BjsOrgGtkGDBusExampleObjectManagerAnimal *object, const gchar *value);


/* ---- */

#define BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_PROXY (bjs_org_gtk_gdbus_example_object_manager_animal_proxy_get_type ())
#define BJS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_PROXY, BjsOrgGtkGDBusExampleObjectManagerAnimalProxy))
#define BJS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_PROXY, BjsOrgGtkGDBusExampleObjectManagerAnimalProxyClass))
#define BJS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_PROXY, BjsOrgGtkGDBusExampleObjectManagerAnimalProxyClass))
#define BJS_IS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_PROXY))
#define BJS_IS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_PROXY))

typedef struct _BjsOrgGtkGDBusExampleObjectManagerAnimalProxy BjsOrgGtkGDBusExampleObjectManagerAnimalProxy;
typedef struct _BjsOrgGtkGDBusExampleObjectManagerAnimalProxyClass BjsOrgGtkGDBusExampleObjectManagerAnimalProxyClass;
typedef struct _BjsOrgGtkGDBusExampleObjectManagerAnimalProxyPrivate BjsOrgGtkGDBusExampleObjectManagerAnimalProxyPrivate;

struct _BjsOrgGtkGDBusExampleObjectManagerAnimalProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  BjsOrgGtkGDBusExampleObjectManagerAnimalProxyPrivate *priv;
};

struct _BjsOrgGtkGDBusExampleObjectManagerAnimalProxyClass
{
  GDBusProxyClass parent_class;
};

GType bjs_org_gtk_gdbus_example_object_manager_animal_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (BjsOrgGtkGDBusExampleObjectManagerAnimalProxy, g_object_unref)
#endif

void bjs_org_gtk_gdbus_example_object_manager_animal_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
BjsOrgGtkGDBusExampleObjectManagerAnimal *bjs_org_gtk_gdbus_example_object_manager_animal_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
BjsOrgGtkGDBusExampleObjectManagerAnimal *bjs_org_gtk_gdbus_example_object_manager_animal_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void bjs_org_gtk_gdbus_example_object_manager_animal_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
BjsOrgGtkGDBusExampleObjectManagerAnimal *bjs_org_gtk_gdbus_example_object_manager_animal_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
BjsOrgGtkGDBusExampleObjectManagerAnimal *bjs_org_gtk_gdbus_example_object_manager_animal_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_SKELETON (bjs_org_gtk_gdbus_example_object_manager_animal_skeleton_get_type ())
#define BJS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_SKELETON, BjsOrgGtkGDBusExampleObjectManagerAnimalSkeleton))
#define BJS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_SKELETON, BjsOrgGtkGDBusExampleObjectManagerAnimalSkeletonClass))
#define BJS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_SKELETON, BjsOrgGtkGDBusExampleObjectManagerAnimalSkeletonClass))
#define BJS_IS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_SKELETON))
#define BJS_IS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_ANIMAL_SKELETON))

typedef struct _BjsOrgGtkGDBusExampleObjectManagerAnimalSkeleton BjsOrgGtkGDBusExampleObjectManagerAnimalSkeleton;
typedef struct _BjsOrgGtkGDBusExampleObjectManagerAnimalSkeletonClass BjsOrgGtkGDBusExampleObjectManagerAnimalSkeletonClass;
typedef struct _BjsOrgGtkGDBusExampleObjectManagerAnimalSkeletonPrivate BjsOrgGtkGDBusExampleObjectManagerAnimalSkeletonPrivate;

struct _BjsOrgGtkGDBusExampleObjectManagerAnimalSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  BjsOrgGtkGDBusExampleObjectManagerAnimalSkeletonPrivate *priv;
};

struct _BjsOrgGtkGDBusExampleObjectManagerAnimalSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType bjs_org_gtk_gdbus_example_object_manager_animal_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (BjsOrgGtkGDBusExampleObjectManagerAnimalSkeleton, g_object_unref)
#endif

BjsOrgGtkGDBusExampleObjectManagerAnimal *bjs_org_gtk_gdbus_example_object_manager_animal_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for org.gtk.GDBus.Example.ObjectManager.Cat */

#define BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT (bjs_org_gtk_gdbus_example_object_manager_cat_get_type ())
#define BJS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT, BjsOrgGtkGDBusExampleObjectManagerCat))
#define BJS_IS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT))
#define BJS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT, BjsOrgGtkGDBusExampleObjectManagerCatIface))

struct _BjsOrgGtkGDBusExampleObjectManagerCat;
typedef struct _BjsOrgGtkGDBusExampleObjectManagerCat BjsOrgGtkGDBusExampleObjectManagerCat;
typedef struct _BjsOrgGtkGDBusExampleObjectManagerCatIface BjsOrgGtkGDBusExampleObjectManagerCatIface;

struct _BjsOrgGtkGDBusExampleObjectManagerCatIface
{
  GTypeInterface parent_iface;
};

GType bjs_org_gtk_gdbus_example_object_manager_cat_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *bjs_org_gtk_gdbus_example_object_manager_cat_interface_info (void);
guint bjs_org_gtk_gdbus_example_object_manager_cat_override_properties (GObjectClass *klass, guint property_id_begin);


/* ---- */

#define BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_PROXY (bjs_org_gtk_gdbus_example_object_manager_cat_proxy_get_type ())
#define BJS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_PROXY, BjsOrgGtkGDBusExampleObjectManagerCatProxy))
#define BJS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_PROXY, BjsOrgGtkGDBusExampleObjectManagerCatProxyClass))
#define BJS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_PROXY, BjsOrgGtkGDBusExampleObjectManagerCatProxyClass))
#define BJS_IS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_PROXY))
#define BJS_IS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_PROXY))

typedef struct _BjsOrgGtkGDBusExampleObjectManagerCatProxy BjsOrgGtkGDBusExampleObjectManagerCatProxy;
typedef struct _BjsOrgGtkGDBusExampleObjectManagerCatProxyClass BjsOrgGtkGDBusExampleObjectManagerCatProxyClass;
typedef struct _BjsOrgGtkGDBusExampleObjectManagerCatProxyPrivate BjsOrgGtkGDBusExampleObjectManagerCatProxyPrivate;

struct _BjsOrgGtkGDBusExampleObjectManagerCatProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  BjsOrgGtkGDBusExampleObjectManagerCatProxyPrivate *priv;
};

struct _BjsOrgGtkGDBusExampleObjectManagerCatProxyClass
{
  GDBusProxyClass parent_class;
};

GType bjs_org_gtk_gdbus_example_object_manager_cat_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (BjsOrgGtkGDBusExampleObjectManagerCatProxy, g_object_unref)
#endif

void bjs_org_gtk_gdbus_example_object_manager_cat_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
BjsOrgGtkGDBusExampleObjectManagerCat *bjs_org_gtk_gdbus_example_object_manager_cat_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
BjsOrgGtkGDBusExampleObjectManagerCat *bjs_org_gtk_gdbus_example_object_manager_cat_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void bjs_org_gtk_gdbus_example_object_manager_cat_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
BjsOrgGtkGDBusExampleObjectManagerCat *bjs_org_gtk_gdbus_example_object_manager_cat_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
BjsOrgGtkGDBusExampleObjectManagerCat *bjs_org_gtk_gdbus_example_object_manager_cat_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_SKELETON (bjs_org_gtk_gdbus_example_object_manager_cat_skeleton_get_type ())
#define BJS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_SKELETON, BjsOrgGtkGDBusExampleObjectManagerCatSkeleton))
#define BJS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_SKELETON, BjsOrgGtkGDBusExampleObjectManagerCatSkeletonClass))
#define BJS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_SKELETON, BjsOrgGtkGDBusExampleObjectManagerCatSkeletonClass))
#define BJS_IS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_SKELETON))
#define BJS_IS_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), BJS_TYPE_ORG_GTK_GDBUS_EXAMPLE_OBJECT_MANAGER_CAT_SKELETON))

typedef struct _BjsOrgGtkGDBusExampleObjectManagerCatSkeleton BjsOrgGtkGDBusExampleObjectManagerCatSkeleton;
typedef struct _BjsOrgGtkGDBusExampleObjectManagerCatSkeletonClass BjsOrgGtkGDBusExampleObjectManagerCatSkeletonClass;
typedef struct _BjsOrgGtkGDBusExampleObjectManagerCatSkeletonPrivate BjsOrgGtkGDBusExampleObjectManagerCatSkeletonPrivate;

struct _BjsOrgGtkGDBusExampleObjectManagerCatSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  BjsOrgGtkGDBusExampleObjectManagerCatSkeletonPrivate *priv;
};

struct _BjsOrgGtkGDBusExampleObjectManagerCatSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType bjs_org_gtk_gdbus_example_object_manager_cat_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (BjsOrgGtkGDBusExampleObjectManagerCatSkeleton, g_object_unref)
#endif

BjsOrgGtkGDBusExampleObjectManagerCat *bjs_org_gtk_gdbus_example_object_manager_cat_skeleton_new (void);


G_END_DECLS

#endif /* __MY_GEN_H__ */
